### ISSUE TITLE
No module named 'spacy' in Job of Travis CI

### ISSUE THREAD

**Issue by sbrunomello** [gunthercox/chatterbot-corpus#227]
Part of log:<br>
``Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/travis/build/gunthercox/chatterbot-corpus/tests/test_data.py", line 5, in <module>
    from chatterbot import corpus
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chatterbot/storage/__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chatterbot/storage/storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosLemmaTagger
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/chatterbot/tagging.py", line 3, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'``

**Comment by WeileiZeng** [comment]
you need to install spacy

e.g. `pip install spacy`

**Comment by gunthercox** [comment]
Revisiting this, I've disabled the Travis job entirely since they've changed their pricing tires. Pull requests should be able to be merged now and I'll do manual checks before doing releases (until I can get an equivalent GitHub actions workflow set up)
